In [1]:
import numpy as np

In [2]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([[1,2,3,4,5]])

In [3]:
print(f'{x1} berbentuk {x1.shape}')
print(f'{x2} berbentuk {x2.shape}')

[1 2 3 4 5] berbentuk (5,)
[[1 2 3 4 5]] berbentuk (1, 5)


In [4]:
x3 = np.dot(x1,x2)

ValueError: shapes (5,) and (1,5) not aligned: 5 (dim 0) != 1 (dim 0)

In [9]:
x3 = x1.reshape(-1,1)
print(f'{x3} berbentuk {x3.shape}')

[[1]
 [2]
 [3]
 [4]
 [5]] berbentuk (5, 1)


In [11]:
x4 = np.dot(x2,x3)
print(x4)

[[55]]


In [12]:
x5 = np.dot(x3,x2)
print(x5)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [13]:
x6 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [16]:
x7 = np.arange(9)
print(x7)

[0 1 2 3 4 5 6 7 8]


In [20]:
x8 = np.random.rand(10)
print(x8)

[0.18985582 0.89981181 0.14996184 0.07838759 0.59160912 0.38510233
 0.75878967 0.70542988 0.29601604 0.87461928]


In [23]:
x9 = np.random.randint(0,100,50)
print(x9.shape)
print(x9)

(50,)
[24 91 31 24 69 35 32 61 31 60 99 18 50 10  8 85 68 18 15 96 20 98 69 12
 63 59 91 16 68 57 33 84  5 53 33 53 97 63 63 17 20 40 95 41  1 75 70 87
 64 60]


In [42]:
print(x9[23:48])
print(x9[23:48:4])
print(x9[-5:])
print(x9[:5])
print(x9[0])
print(x9[-1])
print(np.sum(x9))
print(np.mean(x9))
print(-x9)

[12 63 59 91 16 68 57 33 84  5 53 33 53 97 63 63 17 20 40 95 41  1 75 70
 87]
[12 16 84 53 17 41 87]
[75 70 87 64 60]
[24 91 31 24 69]
24
60
2532
50.64
[-24 -91 -31 -24 -69 -35 -32 -61 -31 -60 -99 -18 -50 -10  -8 -85 -68 -18
 -15 -96 -20 -98 -69 -12 -63 -59 -91 -16 -68 -57 -33 -84  -5 -53 -33 -53
 -97 -63 -63 -17 -20 -40 -95 -41  -1 -75 -70 -87 -64 -60]


In [29]:
x10 = np.random.random_sample(4)
print(x10)

[0.82565928 0.95999842 0.49329927 0.71842126]


In [31]:
x11 = np.zeros(3)
print(x11)

[0. 0. 0.]


In [32]:
x12 = np.ones(3)
print(x12)

[1. 1. 1.]


In [34]:
x13 = np.zeros((2,3))
print(x13)

[[0. 0. 0.]
 [0. 0. 0.]]


In [45]:
x14 = 3*(x13 + 2)
print(x14)

[[6. 6. 6.]
 [6. 6. 6.]]


In [46]:
x15 = np.array([1,23,2,231,2])
x16 = np.array([2,3,21,213,21])
print(np.dot(x15,x16))

49358


In [57]:
x17 = np.random.random_sample((3,3))

In [58]:
print(x17)

[[0.43212112 0.4857402  0.72822669]
 [0.41175704 0.14589896 0.53313534]
 [0.36849429 0.35477395 0.41421308]]


In [67]:
print(x17[1,0])
print(x17[:,2])
print(x17[1,:])
print(x17[0,-2:])

0.4117570395645902
[0.72822669 0.53313534 0.41421308]
[0.41175704 0.14589896 0.53313534]
[0.4857402  0.72822669]


In [71]:
x18 = np.random.random_sample((3,3))
print(x18)

[[0.21068758 0.8808467  0.81857616]
 [0.80012869 0.2260631  0.05624981]
 [0.25867764 0.84758033 0.99552924]]


In [72]:
x19 = x17 @ x18 # Matrix Multiplication

In [73]:
print(x19)

[[0.66807318 1.10767102 1.10601781]
 [0.34140023 0.84755223 0.87601311]
 [0.46864965 0.75586714 0.73395784]]


In [74]:
x20 = np.array([[3,5,12],
                [4,65,23],
                [123,2,0]])
x21 = x20 + 3

In [75]:
print(x21)

[[  6   8  15]
 [  7  68  26]
 [126   5   3]]


In [76]:
x22 = np.linalg.inv(x21)

In [77]:
print(x22)

[[-0.00072899 -0.00050241  0.00799913]
 [-0.03206549  0.01844135  0.00050241]
 [ 0.08405986 -0.00963442 -0.0034676 ]]


In [78]:
eig_val,eig_vect = np.linalg.eig(x22)

In [80]:
print(eig_vect)
print(eig_val)

[[ 0.28715537  0.21357072  0.172003  ]
 [ 0.21239772 -0.63015725  0.92246934]
 [-0.93403908  0.74651818  0.3456375 ]]
[-0.02711962  0.0287137   0.01265069]


In [83]:
x23 = np.array([[1,2,3],
                [4,5,6]])
x24 = x23.reshape(3,-1)

In [84]:
print(x24)

[[1 2]
 [3 4]
 [5 6]]


In [85]:
x25 = x23.T

In [86]:
print(x25)

[[1 4]
 [2 5]
 [3 6]]
