In [2]:
import numpy as np

In [ ]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([[1,2,3,4,5]])

In [ ]:
print(f'{x1} berbentuk {x1.shape}')
print(f'{x2} berbentuk {x2.shape}')

In [ ]:
x3 = np.dot(x1,x2)

In [ ]:
x3 = x1.reshape(-1,1)
print(f'{x3} berbentuk {x3.shape}')

In [ ]:
x4 = np.dot(x2,x3)
print(x4)

In [ ]:
x5 = np.dot(x3,x2)
print(x5)

In [ ]:
x6 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [ ]:
x7 = np.arange(9)
print(x7)

In [ ]:
x8 = np.random.rand(10)
print(x8)

In [ ]:
x9 = np.random.randint(0,100,50)
print(x9.shape)
print(x9)

In [ ]:
print(x9[23:48])
print(x9[23:48:4])
print(x9[-5:])
print(x9[:5])
print(x9[0])
print(x9[-1])
print(np.sum(x9))
print(np.mean(x9))
print(-x9)

In [ ]:
x10 = np.random.random_sample(4)
print(x10)

In [ ]:
x11 = np.zeros(3)
print(x11)

In [ ]:
x12 = np.ones(3)
print(x12)

In [ ]:
x13 = np.zeros((2,3))
print(x13)

In [ ]:
x14 = 3*(x13 + 2)
print(x14)

In [ ]:
x15 = np.array([1,23,2,231,2])
x16 = np.array([2,3,21,213,21])
print(np.dot(x15,x16))

In [ ]:
x17 = np.random.random_sample((3,3))

In [ ]:
print(x17)

In [ ]:
print(x17[1,0])
print(x17[:,2])
print(x17[1,:])
print(x17[0,-2:])

In [ ]:
x18 = np.random.random_sample((3,3))
print(x18)

In [ ]:
x19 = x17 @ x18 # Matrix Multiplication

In [ ]:
print(x19)

In [ ]:
x20 = np.array([[3,5,12],
                [4,65,23],
                [123,2,0]])
x21 = x20 + 3

In [ ]:
print(x21)

In [ ]:
x22 = np.linalg.inv(x21)

In [ ]:
print(x22)

In [ ]:
eig_val,eig_vect = np.linalg.eig(x22)

In [ ]:
print(eig_vect)
print(eig_val)

In [ ]:
x23 = np.array([[1,2,3],
                [4,5,6]])
x24 = x23.reshape(3,-1)

In [ ]:
print(x24)

In [ ]:
x25 = x23.T

In [ ]:
print(x25)

In [4]:
x26 = np.array((np.random.randint(500,2000,3),np.random.randint(0,10,3)))

In [5]:
print(x26)

[[ 679  945 1520]
 [   7    9    4]]


In [8]:
x27 = x26.T

In [9]:
print(x27)

[[ 679    7]
 [ 945    9]
 [1520    4]]


In [15]:
mean = np.mean(x27,axis=0)
print(mean[0])
print(mean[1])

1048.0
6.666666666666667


In [16]:
x28 = x27[:,0] - mean[0]
x28

array([-369., -103.,  472.])

In [17]:
x29 = x27[:,1] - mean[1]
x29

array([ 0.33333333,  2.33333333, -2.66666667])

In [32]:
x30 = np.round(np.array((x28,x29)).T,2)
print(x30)

[[-3.69e+02  3.30e-01]
 [-1.03e+02  2.33e+00]
 [ 4.72e+02 -2.67e+00]]


In [70]:
x31 = np.array([[1,2,3],
                [4,5,6]])
np.mean(x31,axis=0)

array([2.5, 3.5, 4.5])

In [51]:
try:
    m,n = x31.shape
except:
    m = x31.shape[0]
    n = 0
print(n)

3


In [58]:
np.max(x31[:,2])

6

In [61]:
x31[:,0] = x31[:,0] - 3
print(x31)

[[-2  2  3]
 [ 1  5  6]]


In [65]:
x31[:,1] -= 1
print(x31)

[[-2  2  3]
 [ 1  5  6]]


In [66]:
x31[:,2] = x31[:,2] / 2
print(x31)

[[-2  2  1]
 [ 1  5  3]]


In [71]:
mu = np.std(x31,axis=0)
mu

array([1.5, 1.5, 1.5])

In [5]:
x32 = np.array([1,2,3])
x33 = np.array([4,5,6])
x34 = np.c_[x32,x33]
x35 = np.c_[x32,x33,x34]

print(x35)


[[1 4 1 4]
 [2 5 2 5]
 [3 6 3 6]]


In [3]:
x36 = np.array([0,1,1,0,1,1,0])

In [5]:
len(set(x36))

2

In [43]:
x37 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12],
                [13,14,15]])

In [48]:
cond1 = x37[:,0]>0

In [53]:
cond2 = x37[:,0]<11

In [54]:
cond3 = x37[:,2]<10

In [55]:
cond = (cond1+cond2)*cond3

In [56]:
x37[cond,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
x38 = np.arange(5)

In [59]:
x37[:,0]>x38

array([ True,  True,  True,  True,  True])