In [1]:
import numpy as np

In [2]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([[1,2,3,4,5]])

In [3]:
print(f'{x1} berbentuk {x1.shape}')
print(f'{x2} berbentuk {x2.shape}')

[1 2 3 4 5] berbentuk (5,)
[[1 2 3 4 5]] berbentuk (1, 5)


In [4]:
x3 = np.dot(x1,x2)

ValueError: shapes (5,) and (1,5) not aligned: 5 (dim 0) != 1 (dim 0)

In [9]:
x3 = x1.reshape(-1,1)
print(f'{x3} berbentuk {x3.shape}')

[[1]
 [2]
 [3]
 [4]
 [5]] berbentuk (5, 1)


In [11]:
x4 = np.dot(x2,x3)
print(x4)

[[55]]


In [12]:
x5 = np.dot(x3,x2)
print(x5)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [13]:
x6 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [16]:
x7 = np.arange(9)
print(x7)

[0 1 2 3 4 5 6 7 8]
