In [1]:
import numpy as np

In [ ]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([[1,2,3,4,5]])

In [ ]:
print(f'{x1} berbentuk {x1.shape}')
print(f'{x2} berbentuk {x2.shape}')

In [ ]:
x3 = np.dot(x1,x2)

In [ ]:
x3 = x1.reshape(-1,1)
print(f'{x3} berbentuk {x3.shape}')

In [ ]:
x4 = np.dot(x2,x3)
print(x4)

In [ ]:
x5 = np.dot(x3,x2)
print(x5)

In [ ]:
x6 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [ ]:
x7 = np.arange(9)
print(x7)

In [ ]:
x8 = np.random.rand(10)
print(x8)

In [ ]:
x9 = np.random.randint(0,100,50)
print(x9.shape)
print(x9)

In [ ]:
print(x9[23:48])
print(x9[23:48:4])
print(x9[-5:])
print(x9[:5])
print(x9[0])
print(x9[-1])
print(np.sum(x9))
print(np.mean(x9))
print(-x9)

In [ ]:
x10 = np.random.random_sample(4)
print(x10)

In [ ]:
x11 = np.zeros(3)
print(x11)

In [ ]:
x12 = np.ones(3)
print(x12)

In [ ]:
x13 = np.zeros((2,3))
print(x13)

In [ ]:
x14 = 3*(x13 + 2)
print(x14)

In [ ]:
x15 = np.array([1,23,2,231,2])
x16 = np.array([2,3,21,213,21])
print(np.dot(x15,x16))

In [ ]:
x17 = np.random.random_sample((3,3))

In [ ]:
print(x17)

In [ ]:
print(x17[1,0])
print(x17[:,2])
print(x17[1,:])
print(x17[0,-2:])

In [ ]:
x18 = np.random.random_sample((3,3))
print(x18)

In [ ]:
x19 = x17 @ x18 # Matrix Multiplication

In [ ]:
print(x19)

In [ ]:
x20 = np.array([[3,5,12],
                [4,65,23],
                [123,2,0]])
x21 = x20 + 3

In [ ]:
print(x21)

In [ ]:
x22 = np.linalg.inv(x21)

In [ ]:
print(x22)

In [ ]:
eig_val,eig_vect = np.linalg.eig(x22)

In [ ]:
print(eig_vect)
print(eig_val)

In [ ]:
x23 = np.array([[1,2,3],
                [4,5,6]])
x24 = x23.reshape(3,-1)

In [ ]:
print(x24)

In [ ]:
x25 = x23.T

In [ ]:
print(x25)

In [4]:
x26 = np.array((np.random.randint(500,2000,3),np.random.randint(0,10,3)))

In [5]:
print(x26)

[[ 679  945 1520]
 [   7    9    4]]


In [8]:
x27 = x26.T

In [9]:
print(x27)

[[ 679    7]
 [ 945    9]
 [1520    4]]
