# Supervised Learning Algorithm

## 1. Linier Regression

Mengimport packages yang dibutuhkan:

In [1]:
import numpy as np

Menyiapkan Dataset:

In [2]:
# x sebagai input dengan 50 contoh data dan 3 features
x = np.round(np.random.random((50,3))*100,2) 

In [3]:
# Melihat 5 contoh sample data awal
print(x[:5])

[[76.08 14.56 26.45]
 [77.42 16.33 19.85]
 [50.29 36.76 16.42]
 [91.89 63.55 16.38]
 [23.78 33.72 27.66]]


In [4]:
y = np.round(np.random.rand(50)*100,2)
print(y)

[62.5  17.96 87.63 65.3  89.21 99.42 50.19 55.31 27.87 29.43  2.37  5.44
 73.21 49.67 78.01  0.66 10.39 60.51 76.17 45.8   0.13 68.37 60.93 41.06
 49.15 65.8  60.77  6.29 40.35  2.17 24.3  69.61 26.67 59.76  0.99 51.39
 21.42 52.05  1.96 91.89 51.16 72.38  7.1   4.31 49.82  5.4  65.67  6.35
 91.13 86.53]


In [5]:
# Melihat dimensi dataset
print(x.shape)
print(y.shape)

(50, 3)
(50,)


Membuat fungsi $f_{w,b}(x) = w.x + b$ 

In [6]:
# inisiasi variabel weight dan bias
try:
    w = np.zeros(x.shape[1]).reshape(-1,)
except:
    w = np.zeros(1).reshape(-1,)
b = 0

In [9]:
# membuat fungsi f_wb
def f_wb(x,w,b):
    f_wb = np.dot(x,w) + b
    return f_wb

Membuat cost function $J(w,b) = 1/2m \sum{(w.x + b - y)^2}$

In [19]:
def j_wb(x,y,w,b):
    m = y.shape[0]
    fwb = f_wb(x,w,b)
    j = np.round(1/(2*m) * np.sum((fwb - y)**2),5)
    return j

Contoh #1

In [23]:
# Contoh
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
y = np.array([16,32,51])
w = np.ones(x.shape[1])*2
b = 3
fwb = f_wb(x,w,b)
jwb = j_wb(x,y,w,b)
print(f'y: {y} | f_wb: {fwb} | j_wb: {jwb}')

y: [16 32 51] | f_wb: [15. 33. 51.] | j_wb: 0.33333


Gradient Descent untuk mencari nilai minimum J

Langkah 1: Cari nilai turunan dari J terhadap w dan b dan update nilai w dan b

In [9]:
djdw = 1/m * np.dot((f_wb - y),x)
djdb = 1/m * np.sum(f_wb - y)
alpha = 1e-4
w = w - alpha*djdw
b = b - alpha*djdb
print(w,b)

[0.20084234 0.25902811 0.22795835] 0.004443920000000001


Langkah 2: Hitung nilai f_wb dengan parameter w dan b yang baru

In [10]:
# membuat fungsi f_wb
f_wb = np.dot(x,w) + b
print(f_wb)

[25.08547641 24.30855981 23.36975444 38.65504039 19.82023047 56.81114547
 52.6058118  44.25817167 24.82186103 47.78330341 32.5005153  26.82069034
 52.75391682  9.37610947 49.20008177 50.39515736  8.28474841 19.38316384
 56.73361147 32.57165575 54.14392721 36.4973173  51.04600854 30.41517352
 16.16865808 50.07207162 30.94022014 15.71659797 32.48286566 32.61610142
 45.12900492 33.5283207  23.83866561 39.56519664 33.30100785 18.45694713
 25.82883419 11.52841249 16.34619823 36.33884773 26.86517385 51.83043303
 48.69026288 40.55360667 32.72324967 38.61583893 55.10594796 25.56089152
 22.63689914 39.96639707]


Langkah 3: Hitung nilai J dengan fungsi f_wb yang baru

In [11]:
j_wb = 1/(2*m) * np.sum((f_wb - y)**2)
print(j_wb)

518.1643288660698


Langkah 4: Perhatikan hasilnya, jika hasilnya semakin besar maka perkecil alpha dan begitupun sebaliknya

In [12]:
alpha = 1e-5

In [13]:
djdw = 1/m * np.dot((f_wb - y),x)
djdb = 1/m * np.sum(f_wb - y)
w = w - alpha*djdw
b = b - alpha*djdb
print(w,b)

[0.20255179 0.26374254 0.23168154] 0.004545902383376304


In [14]:
# membuat fungsi f_wb
f_wb = np.dot(x,w) + b
print(f_wb)

[25.38275401 24.59189954 23.69026184 39.17281152 20.1229371  57.68729457
 53.35519163 44.88598941 25.1881798  48.4393964  33.00551385 27.21916702
 53.54321629  9.53680119 50.04082198 51.12406257  8.40151564 19.68869598
 57.55596452 33.07944511 54.91828264 37.05915314 51.80801723 30.95749403
 16.37526741 50.92400774 31.44336332 15.95362262 32.94866209 33.17156932
 45.81586522 34.05377811 24.15279387 40.12820436 33.83015555 18.72802723
 26.23319738 11.68903731 16.53670522 36.89284659 27.34629818 52.57725388
 49.43690111 41.1342155  33.26963556 39.12518943 55.9088069  25.87449381
 23.03259876 40.58769105]


In [15]:
j_wb = 1/(2*m) * np.sum((f_wb - y)**2)
print(j_wb)

514.414582882923


Langkah 5: Lakukan hal ini kembali hingga nilai J mendekati nol atau paling minimum

In [16]:
alpha = 2e-4
for i in range(1000):
    djdw = 1/m * np.dot((f_wb - y),x)
    djdb = 1/m * np.sum(f_wb - y)
    w = w - alpha*djdw
    b = b - alpha*djdb
    f_wb = np.dot(x,w) + b
    j_wb = 1/(2*m) * np.sum((f_wb - y)**2)
    print(f'Iterasi ke-{i+1} | MSE: {j_wb:.2f}')

Iterasi ke-1 | MSE: 499.13
Iterasi ke-2 | MSE: 490.22
Iterasi ke-3 | MSE: 484.85
Iterasi ke-4 | MSE: 481.50
Iterasi ke-5 | MSE: 479.36
Iterasi ke-6 | MSE: 477.96
Iterasi ke-7 | MSE: 477.01
Iterasi ke-8 | MSE: 476.37
Iterasi ke-9 | MSE: 475.93
Iterasi ke-10 | MSE: 475.62
Iterasi ke-11 | MSE: 475.40
Iterasi ke-12 | MSE: 475.25
Iterasi ke-13 | MSE: 475.14
Iterasi ke-14 | MSE: 475.06
Iterasi ke-15 | MSE: 475.00
Iterasi ke-16 | MSE: 474.96
Iterasi ke-17 | MSE: 474.93
Iterasi ke-18 | MSE: 474.91
Iterasi ke-19 | MSE: 474.89
Iterasi ke-20 | MSE: 474.88
Iterasi ke-21 | MSE: 474.87
Iterasi ke-22 | MSE: 474.86
Iterasi ke-23 | MSE: 474.85
Iterasi ke-24 | MSE: 474.85
Iterasi ke-25 | MSE: 474.84
Iterasi ke-26 | MSE: 474.84
Iterasi ke-27 | MSE: 474.83
Iterasi ke-28 | MSE: 474.83
Iterasi ke-29 | MSE: 474.83
Iterasi ke-30 | MSE: 474.82
Iterasi ke-31 | MSE: 474.82
Iterasi ke-32 | MSE: 474.82
Iterasi ke-33 | MSE: 474.81
Iterasi ke-34 | MSE: 474.81
Iterasi ke-35 | MSE: 474.80
Iterasi ke-36 | MSE: 474.80
I

Maka didapatkan nilai parameter w dan b teroptimal, sehingga $f_{w,b}(x)$ mendekati nilai $y$

In [17]:
print(f_wb)
print(y)

[18.24025546 17.04022476 23.65680375 36.82885343 24.70517085 70.50982448
 56.13678362 46.9385908  28.66860715 47.30661827 41.16290661 31.33061292
 62.0681834  14.77145003 73.2687362  55.3880373   9.27592621 25.63270732
 62.50251722 41.36170562 58.44487118 45.41964704 59.86765536 49.31884131
 14.12612004 73.99774486 42.75308785 19.45268899 35.08353451 48.90081112
 54.92798643 42.797926   22.10251876 42.03803753 43.95243627 21.54205857
 32.94414075 12.29876536 11.68388136 44.75581493 44.0492448  56.62414247
 59.88331977 44.01694841 46.92567747 35.31828454 61.64177224 20.25034956
 35.66288098 50.50068737]
[62.5  17.96 87.63 65.3  89.21 99.42 50.19 55.31 27.87 29.43  2.37  5.44
 73.21 49.67 78.01  0.66 10.39 60.51 76.17 45.8   0.13 68.37 60.93 41.06
 49.15 65.8  60.77  6.29 40.35  2.17 24.3  69.61 26.67 59.76  0.99 51.39
 21.42 52.05  1.96 91.89 51.16 72.38  7.1   4.31 49.82  5.4  65.67  6.35
 91.13 86.53]


Jika dirasa nilai hasil $f_{w,b}(x)$ kurang maksimal maka lakukan perubahan pada nilai inisiasi w dan b sehingga didapatkan nilai J pada global minima bukan hanya sekedar lokal minima.

In [58]:
w = (np.ones(x.shape[1])*68).reshape(-1,)
b = 68

In [59]:
alpha = 2e-4
f_wb = np.dot(x,w) + b
j_wb = 1/(2*m) * np.sum((f_wb - y)**2)

In [60]:
for i in range(10000):
    djdw = 1/m * np.dot((f_wb - y),x)
    djdb = 1/m * np.sum(f_wb - y)
    w = w - alpha*djdw
    b = b - alpha*djdb
    f_wb = np.dot(x,w) + b
    j_wb = 1/(2*m) * np.sum((f_wb - y)**2)
    print(f'Iterasi ke-{i+1} | MSE: {j_wb:.2f}')

Iterasi ke-1 | MSE: 29033194.89
Iterasi ke-2 | MSE: 14279378.65
Iterasi ke-3 | MSE: 7023877.35
Iterasi ke-4 | MSE: 3455635.33
Iterasi ke-5 | MSE: 1700637.55
Iterasi ke-6 | MSE: 837358.01
Iterasi ke-7 | MSE: 412636.15
Iterasi ke-8 | MSE: 203622.64
Iterasi ke-9 | MSE: 100722.06
Iterasi ke-10 | MSE: 50032.31
Iterasi ke-11 | MSE: 25039.88
Iterasi ke-12 | MSE: 12701.14
Iterasi ke-13 | MSE: 6597.51
Iterasi ke-14 | MSE: 3569.40
Iterasi ke-15 | MSE: 2060.63
Iterasi ke-16 | MSE: 1304.14
Iterasi ke-17 | MSE: 921.36
Iterasi ke-18 | MSE: 725.16
Iterasi ke-19 | MSE: 622.78
Iterasi ke-20 | MSE: 568.06
Iterasi ke-21 | MSE: 537.90
Iterasi ke-22 | MSE: 520.66
Iterasi ke-23 | MSE: 510.39
Iterasi ke-24 | MSE: 504.00
Iterasi ke-25 | MSE: 499.87
Iterasi ke-26 | MSE: 497.09
Iterasi ke-27 | MSE: 495.18
Iterasi ke-28 | MSE: 493.82
Iterasi ke-29 | MSE: 492.85
Iterasi ke-30 | MSE: 492.13
Iterasi ke-31 | MSE: 491.61
Iterasi ke-32 | MSE: 491.22
Iterasi ke-33 | MSE: 490.93
Iterasi ke-34 | MSE: 490.72
Iterasi ke-35