# Supervised Learning Algorithm

## 1. Linier Regression

Mengimport packages yang dibutuhkan:

In [1]:
import numpy as np

Membuat fungsi $f_{w,b}(x) = w.x + b$ 

In [2]:
# membuat fungsi f_wb
def f_wb(x,w,b):
    f_wb = np.dot(x,w) + b
    return f_wb

Membuat cost function $J(w,b) = 1/2m \sum{(w.x + b - y)^2}$

In [3]:
def j_wb(x,y,w,b):
    m = y.shape[0]
    fwb = f_wb(x,w,b)
    j = np.round(1/(2*m) * np.sum((fwb - y)**2),5)
    return j

Contoh #1

In [4]:
# Contoh 1
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
y = np.array([16,32,51])
w_init = np.ones(x.shape[1])*2
b_init = 3
fwb = f_wb(x,w_init,b_init)
jwb = j_wb(x,y,w_init,b_init)
print(f'y: {y} | f_wb: {fwb} | j_wb: {jwb}')

y: [16 32 51] | f_wb: [15. 33. 51.] | j_wb: 0.33333


Gradient Descent untuk mencari nilai minimum J

In [5]:
def graddesc(x,y,w,b,alpha=1e-5,num_iteration=1000):
    m = y.shape[0]
    fwb = f_wb(x,w,b)
    jwb = j_wb(x,y,w,b)
    for _ in range(num_iteration):
        djdw = 1/m * np.dot((fwb - y),x)
        djdb = 1/m * np.sum(fwb - y)
        w = w - alpha*djdw
        b = b - alpha*djdb
        fwb = f_wb(x,w,b)
        jwb = j_wb(x,y,w,b)
    return w,b,fwb,jwb

In [6]:
w,b,fwb,jwb = graddesc(x,y,w_init,b_init,2e-2,10000)

In [7]:
print(w)
print(b)
print(fwb)
print(y)
print(jwb)

[1.66666667 1.94444444 2.22222222]
3.2777777777777657
[15.5 33.  50.5]
[16 32 51]
0.25


Contoh 2